# Generated by Django 2.2.7 on 2020-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200302_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='depart',
            field=models.CharField(max_length=255),
        ),
    ]
