# Generated by Django 2.2.7 on 2020-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='establish_date',
            field=models.IntegerField(max_length=4),
        ),
    ]
