# Generated by Django 2.2.7 on 2020-03-02 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0002_auto_20200302_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='establish_date',
            field=models.IntegerField(verbose_name=django.core.validators.MaxLengthValidator(4)),
        ),
    ]
