# Generated by Django 2.2.7 on 2020-03-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0003_auto_20200302_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='establish_date',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
